version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      - npx mira deploy --file=./infra/src/index.js --env ${ENVIRONMENT} --role "$ROLE_ARN"
  post_build:
    commands:
      - echo Build completed!
artifacts:
  files: '**/*'
