name: Node CI

on:
  - pull_request
  - push

env:
  CI: 1

jobs:
  build-s3-webhosting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up NPM cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Set GitHub Packages Auth Token
      run: npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GH_NPM_READ_TOKEN }}
    - name: Install dependencies
      run: npm ci --prefer-offline
    - name: Build
      run: npm run build
